export default {
  getHomeData:{
    method:'get',
    url:'/mock/homeData.json'
  },
  getNavData:{
    method:'get',
    url:'/mock/navData.json'
  },
  
  getUserData:{
    method:'get',
    url:'/mock/userData.json'
  },
  getUserList:{
    method:'get',
    url:'/mock/userList.json'
  },
  getSearchTableData:{
    method:'get',
    url:'/mock/searchTableData.json'
  },
  getOptionData:{
    method:'get',
    url:'/mock/optionData.json'
  },
  saveTabelData:{
    method:'get',
    url:'/mock/success.json'
  },
  getListData:{
    method:'get',
    url:'/mock/listData.json'
  },
  getDetailData:{
    method:'get',
    url:'/mock/detailData.json'
  },
  
}
